import type { Metadata } from 'next';
import './globals.scss';
import StyledComponentsRegistry from '@/libs/registry';
import Navbar from '@/components/navbar';
import Theme from '@/theme/provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <Theme>{children}</Theme>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
